// AUTOGENERATED: frasi codificate XOR+Base64
const SALT = 'RDF#2025';
const FRASI_ENC = [
  {
    "categoria": "DETTI",
    "testoEnc": "HgVmcWd/ZnQNdHUeCAcDdH9gYXh+cQ=="
  },
  {
    "categoria": "CAPITALE",
    "testoEnc": "AAsLYhLzuhVhcRERBRZqZnF+cA10FhsQB297cQ=="
  },
  {
    "categoria": "MONUMENTO",
    "testoEnc": "GwhmYH18fWZ+dX1yFw8DZmJ9Y2wQc3IWCW5z"
  },
  {
    "categoria": "FIUME",
    "testoEnc": "GwhmZXtlf3ANYHqR3WZvZ351eg10FBsQB297cRL2pRB6HmQWbA=="
  },
  {
    "categoria": "ARTE",
    "testoEnc": "HgEJbXNidnoNdHVyEg9tcXkScH9xFAINEnd9YncVaBB9HBIDbWZ/YHA="
  },
  {
    "categoria": "TORRE",
    "testoEnc": "HgVmd31iYHANdHxyFA9wcxDxvQ1gcBwAA21mdQ=="
  },
  {
    "categoria": "BANDIERA",
    "testoEnc": "HgVmYXN+dnxoYndyDRJifnlze2wQ9dpkEGZgdHcVb3l3HAcJA3cQYHp+Y3k="
  },
  {
    "categoria": "STORIA",
    "testoEnc": "GwhmcXt+c2ZueXoXChJsEvO6FWNxYx1kD20SeWZ0YXl2"
  },
  {
    "categoria": "MONTAGNA",
    "testoEnc": "Gwhmbn1+ZnANcnETCgVsEvO6FXlieXINEmJ+eXMVaBB+AAUIYHtx"
  },
  {
    "categoria": "SCIENZA",
    "testoEnc": "FQUKan51fRVqcXUbCANqEn9hZmhib5HWZm93EGFhaHx1Fw=="
  },
  {
    "categoria": "UNITA",
    "testoEnc": "HmMTbXtk8bUNdRcbEAdve3ESc3gRfhcIZhIKBgM="
  },
  {
    "categoria": "VULCANO",
    "testoEnc": "GwhmdXdjZ2NkfhGRzGZ2fBBkYGFycBwLZmJmZHtjYg=="
  },
  {
    "categoria": "CUCINA",
    "testoEnc": "HgVmc3tqaHQN8rpyCgd3cxBzFWNwYh0IDw=="
  },
  {
    "categoria": "TEATRO",
    "testoEnc": "Gwhmd3dxZmdiEXIeCAcDYXNzeWwR8NpkBwN/eX50Y34="
  },
  {
    "categoria": "MARE",
    "testoEnc": "GwhmbnNidxVsdWYbBRJqcX8Sd2x2ehNkCgR7ZHN5ZHA="
  },
  {
    "categoria": "LETTERATURA",
    "testoEnc": "FgUId3cQc3lkdn0bARRqEmNxZ2RiZhdkCmISdHtjZH90cgcJbn91dnxs"
  },
  {
    "categoria": "CANTANTE",
    "testoEnc": "HhEFan0QcHR5ZX8BEA8DenESdmx/YhMQCQN3fX1vZH54Gw=="
  },
  {
    "categoria": "VOCE",
    "testoEnc": "Hw0IYhLzuhV4f3ZyAANvfnUSY2JyfnIUD+CrEHR0YH5kFw=="
  },
  {
    "categoria": "FESTIVAL",
    "testoEnc": "AQUIcXd9fRXuuRgHCmZld2NmfHtwdHIAA29+cRJ2bH9iHQoDA3tkc3lkcHYT"
  },
  {
    "categoria": "BRANO",
    "testoEnc": "BAUVYH0QYHp+YnByDAcDYXNgfHlldnIFCmFzc3p8bGN4"
  },
  {
    "categoria": "OPERA",
    "testoEnc": "HgVmd2BxZHxsZnFyh84DZ34Ven13YhNkAmoSZndnaXs="
  },
  {
    "categoria": "EUROVISION",
    "testoEnc": "G2QLYnx1YX5kfBEaBQhtfRBkfGNmfnIIYWZnYn1jZGF4HQo="
  },
  {
    "categoria": "TENORE",
    "testoEnc": "EwoCcXdxEndicXceCA8D8bgSYGMSZhcKCXF3EHR0YH1hHQ=="
  },
  {
    "categoria": "COLONNE",
    "testoEnc": "FwoIan0Qf3p/YHoRCwhmEnhzFW59fgILFXd9EHF6YX19HAFmcH1+fWdo"
  },
  {
    "categoria": "CANTAUTORE",
    "testoEnc": "FAUEcXtqe3oNdnFyBQhnYPO7FWVzFAEHFGpmZH0Vb313EQVmZ3sQYHp+cw=="
  },
  {
    "categoria": "POP",
    "testoEnc": "Bg0canN+fRVrd2cAC2ZrcxBxdGNmdAYLZnB3YncVY3dnFw=="
  },
  {
    "categoria": "ORCHESTRA",
    "testoEnc": "HgVmbmdje3ZsEnUeBRVwe3NzFXhhd3IIYWxgc3pwfmZkEw=="
  },
  {
    "categoria": "PIANOFORTE",
    "testoEnc": "Gwhmc3txfHprfWUGAWbguhBne2ISZAYWE253fmZ6DXMXEQsUZ3MQYnB/cXgBFwc="
  },
  {
    "categoria": "ROCK",
    "testoEnc": "GwhmcX1zeRVjc2sRAWZnc3d+fA1zdhwNZmB7fmNgbHxsEw=="
  },
  {
    "categoria": "RAP",
    "testoEnc": "GwhmcXNgEnx5c3UbBQhsEvO6FWR8GREWA3BxeWZ0"
  },
  {
    "categoria": "VOCALE",
    "testoEnc": "FQ0JcXV5cxVlchAHCgcDdWJze2l2EBcXEmZ8Y3t6Y3YQBAsFYn51"
  },
  {
    "categoria": "REGISTA",
    "testoEnc": "FAECZmB5cXoNdXQeCA9texB6dA13eAABEnd9EH50DXd+HgcDA2R5ZnQ="
  },
  {
    "categoria": "OSCAR",
    "testoEnc": "AQsWa3txEnliYXccZA5iEmZ7e3l8EgcKZnNgdX98YhN9AQcHcQ=="
  },
  {
    "categoria": "COMICO",
    "testoEnc": "BgsS4KAQ8b0NZn11DQVsfHEScWh/ExENCGZ/cRJ8eXJ/GwUIbA=="
  },
  {
    "categoria": "FILM",
    "testoEnc": "AAsEZmBkfRVvdnobAwhqEnhzFWl6ZhcQEmwSfHMVe3pgE2SFqxJyd3lhcg=="
  },
  {
    "categoria": "CINEMA",
    "testoEnc": "GwhmYHt+d3hsE/baZAhiZn8SdA11fBwBZmxmZH12aH1hHQ=="
  },
  {
    "categoria": "WESTERN",
    "testoEnc": "AQEUZHt/EnlofHgXZA5iEnNgcGxneXINCgNldWFhaGF4cgUKbxV5ZnRhenccBQ=="
  },
  {
    "categoria": "ATTORE",
    "testoEnc": "HwUUYHd8fnoNfnYBEBRse3F8e2QT9NpkFXdzZH0VeH0XFRYHbXZ1EnR5Z3gAAQ=="
  },
  {
    "categoria": "PARADISO",
    "testoEnc": "FQ0TcHdgYnANZ3cACgd3fWJ3FWVyGBYNFGZmZH0VY2Z3BAtmYHt+d3hsE2gTFgdne2N9"
  },
  {
    "categoria": "CINECITTA",
    "testoEnc": "EQ0IZnF5ZmHusxmRzGZvcxBxdH5yGRYBCgNxeXxwYHIZGxAHb3txfHo="
  },
  {
    "categoria": "SORRENTINO",
    "testoEnc": "AgUJb30QYXp/ZnUcEA9tfRB6dA1weQABEnd9EH50DXNiEwoCZhJyd3lhcWoIBQ=="
  },
  {
    "categoria": "SALVATORES",
    "testoEnc": "FQUEcXt1fnANZ3AeEgd3fWJ3Zg18cHIAD3F3ZGZ6DXl0Fg0SZmBic3toew=="
  },
  {
    "categoria": "MORETTI",
    "testoEnc": "HAUIbXsQf3p/cWYGDWZrcxB2fH9xZgYLZmtzcnd4eGcSAgUWYn8="
  },
  {
    "categoria": "ATTRICE",
    "testoEnc": "HwsIanFxEndoeH8HBwVqEvO6FXh6FBMQEnF7c3cVa3V+HRcH"
  },
  {
    "categoria": "NEOREALISMO",
    "testoEnc": "GwhmbXd/YHBseH0BCQkD8bgSZnl1YB1kE20SfX1jZHlxHBAJA3F5fHBgdWAdAxRidHlxeg=="
  },
  {
    "categoria": "VENEZIA",
    "testoEnc": "GwhmZXdjZnx7dXlyAA8DZHV8cHd9dHKHzgNnfn0VaXF8chQP4KsQc3t5fXYaDQ=="
  },
  {
    "categoria": "CALCIO",
    "testoEnc": "HgVmbXNqe3pjdXoXZA93c3x7dGN1FhYNZmBzfHF8YhR+E2QQanxkfRV8YXcGEBRsEn19e2l9dx4N"
  },
  {
    "categoria": "MOTOGP",
    "testoEnc": "BAUKZnxke3tiFGUdFxVqEvO6FXh6dnIIA2R1dXxxbBRzFwhmbn1kfXJ9"
  },
  {
    "categoria": "CICLISMO",
    "testoEnc": "HwUUYH0QYnRjYHkcDWZrcxBkfGNgd3IDD3F9EHcVeXttAA=="
  },
  {
    "categoria": "NUOTO",
    "testoEnc": "FAECZmB5cXQNZHweCANkYHl8fA18eHIWA2B9YnYVY3FwcnZ2ExJjZnxhcRkeDQRmYH8="
  },
  {
    "categoria": "ROMA",
    "testoEnc": "FBYHbXF1YXZiFWQdEBJqEvO6FXh7cXIGB212eXdnbBV0FwgKYhJifXhs"
  },
  {
    "categoria": "JUVENTUS",
    "testoEnc": "EwgDexJ0d3kNZXgXFgkDenEScmR6chMQCQN8dX55bBV7BxIDbWZlYQ=="
  },
  {
    "categoria": "PORTIERE",
    "testoEnc": "FQ0HbX5le3JkFXAHAgBsfBDxvQ1gfHIUCXFmeXdnaBV+FwMBZnx0c2dkeg=="
  },
  {
    "categoria": "FERRARI",
    "testoEnc": "HgVmZXdiYHR/fBMRCxRxdxB7ew1zfAAJE29zEGd7Yg=="
  },
  {
    "categoria": "ATLETICA",
    "testoEnc": "Ag0Dd2B/Enhoe3oXBWZnd2R7cGNwYhNkD28SYnd2YmdwcgADahICAgUNeHEGFg8="
  },
  {
    "categoria": "DIFESA",
    "testoEnc": "EQEVYmB1EnhseXEbCg8DdxBidGJ5enIJB292eXx8DWZ6HAtmZ3t2d3t+emcbZA9gfX57dmQ="
  },
  {
    "categoria": "SCI",
    "testoEnc": "AQsAanMQdXpqcn8TZA5iEmZ7e3l6FhsKZmB9YGJ0DXFzHmQLbHx0fRVpfBYBBw8="
  },
  {
    "categoria": "EUROPEI",
    "testoEnc": "HmMPd3N8e3QNfXZyEg9tZn8ScmF8FxcRFGxidXsVY3B7cnZ2EQM="
  },
  {
    "categoria": "TENNIS",
    "testoEnc": "GAUIbXt7EmZke3YXFmbguhBnew1hfRwKD3BmcRJ8eXR0GwUIbA=="
  },
  {
    "categoria": "NUOTATORE",
    "testoEnc": "FRYDZH1ie3oNZXgeEBRqfHl3Z2QV+tpkE20Sfmd6eXRtHRYDA3tkc3lkdHcd"
  },
  {
    "categoria": "CALCIO",
    "testoEnc": "Fg0DZH0Qc2dgd34WC2Zuc2JzcWJ4cXKHzgNnfnMVYXN3FQEIZ3MQdnBhFnMTCAVqfQ=="
  },
  {
    "categoria": "MATRIMONIO",
    "testoEnc": "EQEKZnBie2F0FnAcChNtcXlzFWB3ZQANC2x8eX0VbBZiHRYWcXdjcw=="
  },
  {
    "categoria": "MODA",
    "testoEnc": "GwoAb2d1fHZoZBIeBQhge3ESe3h5ZBNkCmp8dXMVaX8SHwsCYg=="
  },
  {
    "categoria": "COPPIA",
    "testoEnc": "ExASbGB5EnFkFmAXFg9mEmRkFX55fR1kD20Sc31lfX9y"
  },
  {
    "categoria": "SOCIAL",
    "testoEnc": "EQUId3N+ZnANZmEQBgpqcXESc2Jie3ISD3FzfHsVfmN9chcJYHtxfg=="
  },
  {
    "categoria": "REALITY",
    "testoEnc": "AAEHb3tkaxV+fnoFZAVxd3ESe3h5YxdkFmx+dX98bn5wcgsIb3t+dw=="
  },
  {
    "categoria": "ROTTURA",
    "testoEnc": "HgVmYH1gYnxsFmAbFGZwexDxvQ16dwEHD2JmcQ=="
  },
  {
    "categoria": "PAPARAZZI",
    "testoEnc": "FAsSbBJgc2VsZHYIHg8Df39hYX93eR1kCHZ9Zn0Va3p+ABA="
  },
  {
    "categoria": "CHEF",
    "testoEnc": "BwpmbX1kfRVufn0UZBZiYHxzFWl/GAcKBwN2eXdhbBZsAAEIZw=="
  },
  {
    "categoria": "PODCAST",
    "testoEnc": "AgsCYHNjZhVpfxkRAQpmcGJ7YXQWahEFCmISfHcVbnp4ARcPZXtzenA="
  },
  {
    "categoria": "GRAVIDANZA",
    "testoEnc": "EwoIdnxze3oNc3lyAxRiZHl2dGNtcXIHCW5/ZX1jaBd5cgIHbQ=="
  },
  {
    "categoria": "SCUSE",
    "testoEnc": "BwpmYHN+ZnRjY3RyBQtud2RmcA1if3IBFHF9YncVZHkRFg0UZmZkcw=="
  },
  {
    "categoria": "BRAND",
    "testoEnc": "BwpmYmZkfWdoF34TCgVqcxBnew16cwAHDmp9EHZ8DWdgHQITbns="
  },
  {
    "categoria": "RITORNO",
    "testoEnc": "BwoHA3F/fHF4Y2cADQVmEmR9Z2N2ExsKZnNgeX90DWR2AAUSYg=="
  },
  {
    "categoria": "CANCELLAZIONE",
    "testoEnc": "BwoHA2Fkc2cNdHUcBwNvfnESYGMXYB0RFAN/f3xxZHZ4Fw=="
  },
  {
    "categoria": "REGIONE",
    "testoEnc": "AAsLYhLzuhVkeRUeBRxqfQ=="
  },
  {
    "categoria": "REGIONE",
    "testoEnc": "Hw0KYnx/EvalF38cZApsf3JzZ2l+dw=="
  },
  {
    "categoria": "FIUME",
    "testoEnc": "Gwhmd3dmd2doF3YGEBRiZHVgZmwXZR0JBw=="
  },
  {
    "categoria": "FOCE",
    "testoEnc": "Gwhmc30QYXNidHETZAhmfhB/dH9yGBMAFGpzZHt2Yg=="
  },
  {
    "categoria": "ISOLA",
    "testoEnc": "HgVmcHtze3lkdhmRzGZvcxB/dGpwcB0WAwN7Y315bBdwBgUKanN+cw=="
  },
  {
    "categoria": "CAPITALE",
    "testoEnc": "HgVmcHNidnBqdnFyDAcDcXFifHl5fBdkBWJ1fHt0f3E="
  },
  {
    "categoria": "VULCANO",
    "testoEnc": "HmMDd3xxEvalGGQcZBB2fnNze2IYcAYQD3V9"
  },
  {
    "categoria": "MONTAGNA",
    "testoEnc": "HgFmZ318fXhkbHtyFwltfRB/emNscxUKAwN2dX55CnlgEQtmYn5ge3ti"
  },
  {
    "categoria": "REGIONE",
    "testoEnc": "FA0UZnxqdxXusBMbCmZ3fWNxdGN5"
  },
  {
    "categoria": "REGIONE",
    "testoEnc": "BgsUanx/EvalGH0cZBZqd319e3l9"
  },
  {
    "categoria": "REGIONE",
    "testoEnc": "BAEIZmh5cxV+cRUGFgl1cxB7ew1ucBwBEmw="
  },
  {
    "categoria": "REGIONE",
    "testoEnc": "HAUWbH55EvalGH8cZAVif2Bze2R5"
  },
  {
    "categoria": "REGIONE",
    "testoEnc": "EAsKbHV+cxXusBcbCmZmf3l+fGwYZR0JB2R8cQ=="
  },
  {
    "categoria": "REGIONE",
    "testoEnc": "AgUKZmB9fRXusBgbCmZwe3N7eWR5"
  },
  {
    "categoria": "REGIONE",
    "testoEnc": "EAUUahLzuhVkdhkCEQFve3E="
  },
  {
    "categoria": "REGIONE",
    "testoEnc": "FQEIbGRxEvalGXkcZApqdWVgfGw="
  },
  {
    "categoria": "AMICI",
    "testoEnc": "Gwhmbnt/EnRgcHIdZAdnfWJzFWF4EQIFFXdzEHN5YXgREQUUYX1+c2ds"
  },
  {
    "categoria": "AMICI",
    "testoEnc": "BwpmYn95cXoNaX0AEAcDYXV/ZX98EhQLFHdnfnMVbHUSFQ0JYH0="
  },
  {
    "categoria": "AMICI",
    "testoEnc": "FQgPA3N9e3ZkGXwAAwdte2podGN2EwcKBwNxdXx0DXgTAQsUc2B1YXQ="
  },
  {
    "categoria": "AMICI",
    "testoEnc": "BwpmYn95cXoNcXVyDQtzc2JzYWIZdXIXE2x8cWBwDXV1cgcOamZxYGds"
  },
  {
    "categoria": "AMICI",
    "testoEnc": "BwpmYn95cXoN+r1yBRZzc2NhfGJ3dAYLZmd7EHF0YXp8HQ=="
  },
  {
    "categoria": "AMICI",
    "testoEnc": "BwoHA3N9e3ZsGXcfBWZqEmZ7dGp+f3INCAN/f3xhbH54Ew=="
  },
  {
    "categoria": "AMICI",
    "testoEnc": "FQgPA3N9e3ZkGXETCghsEmV8dA1+fgYFZmJ+EH90f3w="
  },
  {
    "categoria": "AMICI",
    "testoEnc": "BwpmYn95cXoNenceCAN5e398dA1/bR8BEnd7EGB0f3A="
  },
  {
    "categoria": "AMICI",
    "testoEnc": "BwpmYn95cXoNenYAFgMDfnESeGhjYxNkC2JgcWZ6Y3g="
  },
  {
    "categoria": "AMICI",
    "testoEnc": "FQgPA3N9e3ZkEWZ5HAcJbX0QZ3sNYGV5CGQSZn51ZHx+eGZ/"
  }
];

const FRASI_TEST = [
  {
    "indice": 101,
    "categoria": "TEST",
    "testo": "QUESTA È UNA FRASE DI TEST"
  },
  {
    "indice": 102,
    "categoria": "CULTURAGENERALE",
    "testo": "ROMA È DETTA CITTÀ ETERNA"
  },
  {
    "indice": 103,
    "categoria": "MUSICA",
    "testo": "LA CHITARRA È UNO STRUMENTO A CORDE"
  },
  {
    "indice": 104,
    "categoria": "CINEMA",
    "testo": "UN REGISTA DIRIGE GLI ATTORI"
  },
  {
    "indice": 105,
    "categoria": "SPORT",
    "testo": "NEL CALCIO SI SEGNA UN GOL"
  },
  {
    "indice": 106,
    "categoria": "GOSSIP",
    "testo": "UNA STAR PUBBLICA UNA STORIA SU INSTAGRAM"
  }
];
